### ISSUE TITLE
Another crash :)

### ISSUE THREAD

**Issue by Gamerbolts** [FrenchUranoscopidae/Hated_Mobs#7]
Hi again lol. So the client and server both loaded up fine, no crashes or anything. Then I tried to connect to the server and the server crashed, clients fine. Here is crash report. https://pastebin.com/HYP9Yq4T

**Comment by Gamerbolts** [comment]
Also just realized there is no config file for this mod. Is that a planned thing?

**Comment by FrenchUranoscopidae** [comment]
Hi again ! Thanks for the crash report ! Saddly I won't be able to fix this as quickly as usual, it should be out next week with a mob to put up for the wait ^^
And concerning the config, I will add one in the future, but since it's my very first mod I don't really know how much time it will take me :/

**Comment by Gamerbolts** [comment]
Not a problem, take your time :) I look forward to the update. Thanks!

**Comment by FrenchUranoscopidae** [comment]
Hi ! The new version of the mod will soon be available here : https://minecraft.curseforge.com/projects/hated-mobs/files/2637205
It should fix the issue !

**Comment by Gamerbolts** [comment]
Awesome! Thanks so much
